apiVersion: v1
kind: Pod
metadata:
  name: nginx-https-pod
  namespace: my-nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx/conf.d
      - name: nginx-certs
        mountPath: /etc/nginx/ssl
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-tls-config
    - name: nginx-certs
      secret:
        secretName: nginx-tls-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 38000  # Exposes HTTP on node port 38000
    - name: https
      port: 443
      targetPort: 443
      nodePort: 34430  # Exposes HTTPS on node port 34430
